### PR TITLE
Add tqdm for progress bar

### PR DESCRIPTION
**Pull request by datavistics**

### CODE REVIEW

**Comment by thiswillbeyourgithub** [comment]
Can you confirm you tested this before I merge?

**Comment by datavistics** [comment]
Yes, I just tested that it would operate the loop the same way.

**Comment by datavistics** [comment]
Enumerate is actually unnecessary as you are only using the index for the progress. 
The prints can be upgraded to tqdm.write() so that the progressbar isnt interfered with. 

Edit: Just pushed

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot!

**Pull request merged**
